import { prisma } from "@/lib/prisma";
import { formatAuditAction, formatAuditTimestamp, groupAuditsByDate } from "@/lib/auditFormatter";

interface RecentActivityFeedProps {
  limit?: number;
  userId?: string; // If provided, limits to activities generated by this user or affecting this user
}

export async function RecentActivityFeed({ limit = 20, userId }: RecentActivityFeedProps) {
  const where: any = {};
  if (userId) {
    where.OR = [
      { actorId: userId },
      // Optional: Could expand to filter by entityId if we know the user's sheet ID
    ];
  }

  const rawAudits = await prisma.auditLog.findMany({
    where,
    orderBy: { createdAt: "desc" },
    take: limit,
    include: { actor: true }
  });

  if (rawAudits.length === 0) {
    return (
      <div className="p-8 text-center text-zinc-500 bg-zinc-900/20 border border-zinc-800/80 border-dashed rounded-xl">
        No recent activity found.
      </div>
    );
  }

  const grouped = groupAuditsByDate(rawAudits);

  return (
    <div className="space-y-8">
      {Object.keys(grouped).map((dateGroup, groupIdx) => (
        <div key={dateGroup} className="relative">
          <h4 className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-4 sticky top-0 bg-zinc-950/80 backdrop-blur py-2 z-10">
            {dateGroup}
          </h4>
          
          <div className="space-y-6 relative before:absolute before:inset-0 before:ml-[19px] before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-zinc-800 before:to-transparent">
            {grouped[dateGroup].map((audit: any, i: number) => {
              const { text, icon: Icon, color } = formatAuditAction(audit.action, audit.entityType, audit.newValues);
              
              return (
                <div key={audit.id} className="relative flex items-start group">
                  <div className="flex items-center justify-center w-10 h-10 rounded-full border-[3px] border-zinc-950 bg-zinc-900 z-10 shrink-0 shadow-sm mr-4 ml-0 md:mx-auto md:w-10">
                    <div className={`p-1.5 rounded-full ${color}`}>
                      <Icon size={14} />
                    </div>
                  </div>
                  
                  <div className="flex-1 min-w-0 bg-zinc-900/50 hover:bg-zinc-800/50 transition-colors border border-zinc-800/80 rounded-xl p-4 mt-1 mb-2 shadow-sm">
                    <div className="flex justify-between items-start gap-4">
                      <div>
                        <p className="text-sm text-zinc-300">
                          <span className="font-medium text-zinc-100">{audit.actor.name}</span> {text}
                        </p>
                        {audit.entityType === "GoalSheet" && (
                          <p className="text-xs text-zinc-500 mt-1">Target: Goal Sheet</p>
                        )}
                        {audit.entityType === "Goal" && audit.newValues?.title && (
                          <p className="text-xs text-zinc-500 mt-1">Goal: {audit.newValues.title}</p>
                        )}
                      </div>
                      <span className="text-xs text-zinc-500 whitespace-nowrap">
                        {formatAuditTimestamp(audit.createdAt)}
                      </span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}
