import { prisma } from "@/lib/prisma";
import { formatAuditAction, formatAuditTimestamp, groupAuditsByDate, AuditWithActor } from "@/lib/auditFormatter";

interface RecentActivityFeedProps {
  limit?: number;
  userId?: string; // If provided, limits to activities generated by this user or affecting this user
}

export async function RecentActivityFeed({ limit = 20, userId }: RecentActivityFeedProps) {
  const where: any = {};
  if (userId) {
    where.OR = [
      { actorId: userId },
    ];
  }

  const rawAudits = await prisma.auditLog.findMany({
    where,
    orderBy: { createdAt: "desc" },
    take: limit,
    include: {
      actor: {
        select: {
          id: true,
          name: true,
          role: true,
          empId: true
        }
      }
    }
  });

  if (rawAudits.length === 0) {
    return (
      <div className="p-8 text-center text-zinc-550 bg-zinc-950/20 border border-zinc-900 border-dashed rounded-xl select-none text-xs italic">
        No operational ledger logs recorded.
      </div>
    );
  }

  const grouped = groupAuditsByDate(rawAudits as any);

  return (
    <div className="space-y-6 select-none">
      {Object.keys(grouped).map((dateGroup, groupIdx) => (
        <div key={dateGroup} className="space-y-3">
          <h4 className="text-[9px] font-bold text-zinc-550 uppercase tracking-widest border-b border-zinc-950 pb-1.5 mb-2.5">
            {dateGroup}
          </h4>
          
          <div className="flex flex-col gap-2">
            {grouped[dateGroup].map((audit: any) => {
              const newValues = audit.newValues as Record<string, any> | null | undefined;
              const { text, icon: Icon, color } = formatAuditAction(audit.action, audit.entityType, audit.newValues);
              
              return (
                <div key={audit.id} className="flex items-start gap-3 p-3 bg-zinc-950/15 hover:bg-zinc-900/10 border border-zinc-900/60 rounded-xl transition-all shadow-sm">
                  <div className={`p-1.5 rounded-lg ${color} shrink-0 mt-0.5`}>
                    <Icon size={12} />
                  </div>
                  
                  <div className="flex-1 min-w-0 flex flex-col md:flex-row md:items-center justify-between gap-1">
                    <div className="min-w-0">
                      <p className="text-xs text-zinc-300 font-semibold leading-relaxed">
                        <span className="text-zinc-150 font-bold">{audit.actor?.name || "System"}</span> {text}
                      </p>
                      {audit.entityType === "GoalSheet" && (
                        <p className="text-[10px] text-zinc-550 font-bold uppercase tracking-wider mt-0.5">Target: Quarter Plan</p>
                      )}
                      {audit.entityType === "Goal" && newValues?.title && (
                        <p className="text-[10px] text-zinc-550 font-bold uppercase tracking-wider mt-0.5">Goal: {newValues.title}</p>
                      )}
                    </div>
                    <span className="text-[10px] font-mono text-zinc-650 shrink-0 font-bold md:text-right">
                      {formatAuditTimestamp(audit.createdAt)}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}
